plugins {
    id 'java'
    id 'idea'
    id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version '1.2.1'
    id 'com.diffplug.spotless' version '6.13.0'
    id 'com.hypherionmc.modutils.orion' version '1.0.+'
}
apply plugin: 'maven-publish'

orion.setup {
    enableReleasesMaven = true

    versioning {
        var relType = project.properties["reltype"] ?: "${release_type}"
        identifier("${relType}")
        isUploadBuild = (relType == 'release')
    }
}

group = 'com.hypherionmc.modutils'
description = "Gradle plugin to Upload and Publish mods to CurseForge/Modrinth/Github"
archivesBaseName = 'ModPublisher'
java.toolchain.languageVersion = JavaLanguageVersion.of(8)

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()

    implementation "me.hypherionmc.modutils:CurseUpload4j:${curse4j}"
    implementation 'com.github.masecla22:Modrinth4J:-SNAPSHOT'
    implementation "org.kohsuke:github-api:${github}"
    implementation "org.apache.maven:maven-artifact:${mavenart}"
    implementation "com.hypherionmc.nightbloom:nightbloom4j:${nightbloom}"

    compileOnly "org.projectlombok:lombok:${lombok}"
    annotationProcessor "org.projectlombok:lombok:${lombok}"

    testImplementation "org.junit.jupiter:junit-jupiter-api:${junit}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junit}"

    testCompileOnly "org.projectlombok:lombok:${lombok}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok}"
}

test {
    useJUnitPlatform()
}

gradlePlugin {
    plugins {
        modPublisherPlugin {
            id = 'com.hypherionmc.modutils.modpublisher'
            description = project.description
            displayName = 'ModPublisher'
            version = project.version
            implementationClass = "com.hypherionmc.modpublisher.plugin.ModPublisherPlugin"
            tags.set(['modrinth', 'publish', 'mods', 'github', 'minecraft', 'curseforge'])
        }
    }
}

jar {
    manifest {
        attributes([
                'Timestamp'               : System.currentTimeMillis(),
                'Specification-Title'     : project.archivesBaseName,
                'Specification-Version'   : project.version,
                'Implementation-Title'    : project.archivesBaseName,
                'Implementation-Version'  : project.version,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})"
        ])
    }
}

spotless {
    java {
        targetExclude("src/test/**")
        licenseHeaderFile(rootProject.file("HEADER")).yearSeparator("-")
    }
}

publishing {
    repositories {
        maven orion.getPublishingMaven()
    }
}
